# Generated by Django 4.2.7 on 2024-05-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_see_all_the_users', 'can_see_all_the_users'), ('can_block_users', 'can_block_users')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
