# Generated by Django 4.2.7 on 2024-05-17 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_remove_newsletter_client_newsletter_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='client',
            new_name='clients',
        ),
    ]
