# Generated by Django 4.2.7 on 2024-05-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_rename_client_newsletter_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.message', verbose_name='сообщение'),
        ),
    ]
