# Generated by Django 4.2.7 on 2024-05-28 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0008_alter_client_user_alter_message_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'verbose_name': 'попытка', 'verbose_name_plural': 'попытки'},
        ),
        migrations.AddField(
            model_name='attempt',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.client'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.message'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='newsletter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.newsletter'),
        ),
    ]
