# Generated by Django 4.2.7 on 2024-05-28 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_alter_attempt_options_attempt_client_attempt_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('update_newsletter', 'Can update newsletter')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
