# Generated by Django 4.2.7 on 2024-05-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_alter_newsletter_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='message',
        ),
    ]
