# Generated by Django 4.2.7 on 2024-05-28 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_remove_attempt_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.message'),
        ),
    ]
