# Generated by Django 4.2.7 on 2024-05-28 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0012_attempt_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('update_newsletter', 'Can update newsletter'), ('can_view_any_newsletter', 'can_view_any_newsletter'), ('can_turn_the_newsletter_off', 'can_turn_the_newsletter_off')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
