# Generated by Django 4.2.7 on 2024-05-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0013_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('can_view_any_newsletter', 'can_view_any_newsletter'), ('can_turn_the_newsletter_off', 'can_turn_the_newsletter_off')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='завершено'),
        ),
    ]
