# Generated by Django 4.2.7 on 2024-05-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0014_alter_newsletter_options_newsletter_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='конец рассылки'),
        ),
    ]
