# Generated by Django 4.2.7 on 2024-05-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
